name: GitHub Traffic Badges

on:
  schedule:
    - cron: '0 0 * * *' # Изпълнява се автоматично всяка вечер
  workflow_dispatch: # Позволява Ви ръчно пускане

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch Traffic Data
        uses: yi-Ji/traffic-to-badge@v1.4.0
        with:
          # Използваме главно 'J' и правилната официална версия
          access_token: ${{ secrets.GITHUB_TOKEN }}
